#42 SELECT WHERE IsSqlNull with all Field Types
lansa/db-regression pull request #61
Opened 2024-01-11 02:33 UTC by Manish-Celestial

This pull request is related to #42 

In the first iteration of the PR, all newly added fields along with updated list and tables has been committed

2024-01-11 07:27 UTC, Manish-Celestial commented
Hi @robe070 , I have updated the relevant methods in the test case driver to test *sqlNUll and *sqlNotNull on all the field types.
Attaching a snapshot of DB and verifiertestreport of succesful execution 

![image](https://github.com/lansa/db-regression/assets/153073185/a67fd95d-ff04-4448-91f8-0342ffbe02b9)
[Verifier_Test_Report.txt](https://github.com/lansa/db-regression/files/13898734/Verifier_Test_Report.txt)

2024-01-12 00:10 UTC, robe070 commented on Partition (WBP)/Functions/V56118C.VT156118.fun.yml
> +    Select Fields(*ALL) From_File(VTL156118C) Where((#F156118K2 <> 0) *And (#F156118D.IsSqlnull)) With_Key(#this_key) Io_Status(#this_rc) Io_Error(*NEXT) Val_Error(*NEXT)
You have not changed the WHERE clause in ALL of the SELECT commands. E.g. for this line the WHERE parameter should be:
```
(#F156118K2 <> 0) *And (#BIFB001C.IsSqlnull)
```
I note that the log message before the SELECT and the IF command to test the returned value are using the correct Field.
Please correct all the SELECT commands.

2024-01-12 00:12 UTC, robe070 requested changes
Its good to see that you found other examples of initialising LOBs and Binary fields.

Also you'll need to modify verifier_connection.dat to enable the SQL Server and IBMi SuperServer tests. And also deliver all the object changes to the IBMi before you may run the test.

2024-01-12 03:08 UTC, Manish-Celestial commented
Pushed a new commit, making the changes as needed

2024-01-12 06:17 UTC, robe070 reviewed
Changes look good.
Now just need the final test report with all tests run including Superserver and IBMi.

2024-01-12 07:48 UTC, merged