Issue 43: Select Options - *BACKWARDS, *STARTKEY & *ENDWHERE & *ENDWHERESQL
lansa/db-regression pull request #68
Opened 2024-01-16 13:03 UTC by Manish-Celestial

2024-01-18 08:49 UTC, robe070 reviewed
Thats what I intended. Good work.
I've forced my branch back to before those 3 commits so I could pull your PR.

2024-01-26 06:04 UTC, Manish-Celestial commented
Adding VerifierTestReport for windows platform
[Verifier_Test_Report.txt](https://github.com/lansa/db-regression/files/14060839/Verifier_Test_Report.txt)

2024-01-27 07:15 UTC, robe070 requested changes
The tests are all wrong now because of the keys we changed.

All the tests are effectively finding all rows matching 2, say, and then checking if that key field = 2. Thats not testing anything.

The key is correct. Its BIFN0700A that needs to be tested for EVERY test. Originally the spec had:
_The test data is the same for all the secondary keys, matching BIFC010A._
You changed that secondary key to be BIFN0700A. Thus it is what needs to be compared.
I've commented on one test case as to what needs to change as an example for all the test cases.

2024-01-27 07:15 UTC, robe070 commented on Partition (WBP)/Functions/VI0043C.VTI0043.fun.yml
> +    #LF_BIFU100C := #BIFU100C
Need to add a line here
```
#LF_BIFN0700A := #BIFN0700A
```

2024-01-27 07:15 UTC, robe070 commented on Partition (WBP)/Functions/VI0043C.VTI0043.fun.yml
> +    If (#LF_BIFU100C <> #BIFU100C)
For example this line in every test needs to be 
```
if ( #LF_BIFN0700A <> #BIFN0700A )
```

2024-01-31 22:39 UTC, robe070 requested changes
You need *BACKWARDS  Descending key.

VI0049A seems to be out of date. It does not run VI0049D.

Please add log messages to display the values of the key returned by the SELECTs. Like you put in when we were in the meeting. I need to be clear that the tests are a good one.
Condition each of the tests with a global boolean so they can be easily disabled. E.g. #DetailedLog

2024-01-31 22:41 UTC, robe070 commented
And you need to run the test against IBMi. The results will be different - hence the conditional setting of the expected results for IBMi in V57033F.

2024-02-01 02:17 UTC, satishCodeIndians commented
Submitted Changes, Once the windows platform changes are approved, I will check-in to IBMi and update the test as per the results over there

2024-02-01 04:06 UTC, robe070 requested changes
You need to output the WHERE clause to the log file too.

2024-02-01 04:06 UTC, robe070 commented on Partition (WBP)/Functions/VI0043D.VTI0043.fun.yml
> +    Define Field(#LF_DetailedLog) Reffld(#Std_Count)
I said a boolean
```
Define Field(#LF_DetailedLog) Reffld(#BIFB001B)
```

2024-02-01 04:06 UTC, robe070 commented on Partition (WBP)/Functions/VI0043D.VTI0043.fun.yml
> +    If (#LF_DetailedLog <> 0)
Change all these tests to
```
If (#LF_DetailedLog)
```

2024-02-01 04:07 UTC, robe070 commented
Next time provide me with a detailed log and I can reply sooner.

2024-02-01 04:11 UTC, robe070 commented
The WHERE clause needs to be changed. The very first result set should stop at 111. It doesn't. It goes to 119.
(#BIFINT2S *LE 111) *And (#BIFN0700A *LE 190)) *Or ((#BIFINT2S *GE -111) *And (#BIFN0700A *LE 510))

2024-02-01 07:47 UTC, satishCodeIndians commented
[
[Verifier_Test_Report_I0043D_2.txt](https://github.com/lansa/db-regression/files/14121825/Verifier_Test_Report_I0043D_2.txt)
](url)

2024-02-01 16:10 UTC, satishCodeIndians commented
Super Server tests passing
[Verifier_Test_Report_I0043D_3.txt](https://github.com/lansa/db-regression/files/14127858/Verifier_Test_Report_I0043D_3.txt)

2024-02-01 23:46 UTC, robe070 commented on Partition (WBP)/Functions/VI0043D.VTI0043.fun.yml
> +    #LF_Where_Clause := 'Where(((#BIFINT2S *LE 111) *And (#this_test_value *GE 0)) *Or ((#BIFINT2S *GE -111) *And (#this_test_value *LE 0)))'
Split this in 2
```
#LF_Where_Clause := 'Where(((#BIFINT2S *LE 111) *And (#this_test_value *GE 0)) *Or'
#LF_Where_Clause2 := '((#BIFINT2S *GE -111) *And (#this_test_value *LE 0)))'
#Com_Owner.mthAdd_SubMsg( #this_rc (#this_operation + ' ' + #LF_Where_Clause) #LF_Where_Clause2 )
```

2024-02-01 23:46 UTC, robe070 commented on Partition (WBP)/Functions/VI0043D.VTI0043.fun.yml
> +    #Com_Owner.mthAdd_SubMsg( OK (' Evaluated Condition : Where (' + (#BIFINT2S.AsString) + ' < 111 and' + #this_test_value.AsString + ' > 0 ) or ( ' + (#BIFINT2S.AsString) + ' > -111 and ' + #this_t
Split the WHERE clause across the two params of mthAdd_SubMsg
```
#Com_Owner.mthAdd_SubMsg( OK (' Evaluated Condition : Where (' + (#BIFINT2S.AsString) + ' < 111 and' + #this_test_value.AsString + ' > 0 ) or ') '( ' + (#BIFINT2S.AsString) + ' > -111 and ' + #this_test_value.AsString + ' < 0 )' )
```

2024-02-01 23:53 UTC, robe070 requested changes
I need the changes in order to be able to review that the tests are useful.
A quick turnaround would be useful.

2024-02-01 23:57 UTC, Manish-Celestial commented
Sure, I Pushed the changes and here is the log
[Verifier_Test_Report_I0043_4.txt](https://github.com/lansa/db-regression/files/14132310/Verifier_Test_Report_I0043_4.txt)

2024-02-02 01:12 UTC, robe070 requested changes
Test values are all good.

`*BACKWARDS DESCENDING` has message `*FORWARDS DESCENDING`

Minor issue. add a space here `and-100`:
```
Evaluated Condition : Where (-100 < 111 and-100 > 0 ) or ( -100 > -111 and -100 < 0 )
```

2024-02-02 01:42 UTC, Manish-Celestial commented
Done. Thank you

2024-02-02 07:47 UTC, robe070 commented
The IBMi test is still failing.

2024-02-02 10:10 UTC, Manish-Celestial commented
[Verifier_Test_Report_I0043_5.txt](https://github.com/lansa/db-regression/files/14138578/Verifier_Test_Report_I0043_5.txt)

2024-02-02 10:11 UTC, Manish-Celestial commented
The tests are successful on IBMi with latest changes. Attaching the report

2024-02-02 10:37 UTC, merged